### ISSUE TITLE
Contents Development, Security 

### ISSUE THREAD

**Issue by MichaelTB** [euchungmsft/spring-petclinic-microservices#12]

**Comment by euchungmsft** [comment]
Initially discussed with Israel but there's nothing for this in the demo app. Do you have any good idea ?

**Comment by MichaelTB** [comment]
@euchungmsft I thought they mentioned it during the last meeting.  I will verify tomorrow.

**Comment by euchungmsft** [comment]
I'm curious what particular usecases they want to add for AAD integ

**Comment by MichaelTB** [comment]
I will reconcile the comments from Pruna and Guy with Isreal...there is probably a disconnect or misunderstanding... I will see if either of them are free before my 1:1 with Isreal.

**Comment by MichaelTB** [comment]
@euchungmsft, Isreal stated that Security will be added at some point.  Security will cover concepts like RBAC, Azure AD Integration....etc.
