### ISSUE TITLE
Document updates, rev02

### ISSUE THREAD

**Issue by euchungmsft** [euchungmsft/spring-petclinic-microservices#27]
+ what's changed - listing all changes made in this release since it's forked from Azure-Samples/spring-petclinic-microservices
+ running the app locally for development
+ automated DevOps/DevSecOps in a pipeline - CI/CD, static test, code coverage, unit test, app scanning/pentest, load testing, api monitoring 
+ apim config with swagger
+ G/B, canary release with Azure Spring Cloud 
+ implementations to integrate Azure services
+ how to maintain - how to use this as app template

**Comment by MikeTB-Microsoft** [comment]
@euchungmsft I am reviewing the Pet Clinic Repo. Which files do we actually need for this project?  There are files from years ago, are any of them still relevant to this project?
